@startuml
actor Customer
participant Cart
participant Website
database DBMS
Customer -> Website: Input search criteria for available flights
Website -> DBMS: Search available flights
DBMS -> Website: List of available flights
Website -> Customer: Diplay list of available flights
Customer -> Cart: Select and add flight to shopping cart
Cart -> Website: Render updated shopping cart
Customer -> Website: Go to checkout and enter payment info
Website -> DBMS: Process payment info and create ticket for flight
DBMS -> Website: Provide ticket with seat/plane/flight info
Website -> Cart: Update shopping cart
Cart -> Website: Render updated shopping cart
Website -> Customer: Display confirmed ticket and updated shopping cart
@enduml
